---
name: Preview [SETUP]

on:
  pull_request:
    branches:
      - qa

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_REGION: ${{ vars.GCP_REGION }}
      GCP_SERVICE_ACCOUNT: ${{ vars.GCP_SERVICE_ACCOUNT }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
    steps:
      - name: Check out repository
        id: checkout
        uses: actions/checkout@v4

      - name: Authentication
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Artifact registry login
        uses: docker/login-action@v3
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
          registry: "${{ env.GCP_REGION }}-docker.pkg.dev"
          logout: true

      - name: Fetch
        run: |
          echo "REPOSITORY_NAME: ${{ github.event.repository.name }}
          echo "REPOSITORY_FULL_NAME: $(${{ github.event.pull_request.head.repo.full_name }} | tr '[:upper:]' '[:lower:]')"
          echo "REPOSITORY_PR_NUMBER: ${{ github.event.number }}"
          echo "REPOSITORY_COMMIT_SHA: $(git rev-parse --short ${{ github.sha }})"

      # - name: Build & Push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: |
      #       ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_AR_NAME }}/${{ env.REPOSITORY_FULL_NAME }}:${{ env.REPOSITORY_COMMIT_SHA }}

      # - name: Run
      #   run: |
      #     gcloud run deploy preview-${{ env.REPOSITORY_NAME }}-pr${{ env.REPOSITORY_PR_NUMBER }}-${{ env.REPOSITORY_COMMIT_SHA }} \
      #         --region ${{ env.GCP_REGION }} \
      #         --project ${{ env.GCP_PROJECT_ID }} \
      #         --image=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_AR_NAME }}/${{ env.REPOSITORY_FULL_NAME }}:${{ env.REPOSITORY_COMMIT_SHA }} \
      #         --port=8000 \
      #         --ingress=all \
      #         --allow-unauthenticated
